---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=86400


- name: Install core mysql resources
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - python-mysqldb
    - mysql-server-5.5

- name: Setup the root mysql user
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
  ignore_errors: true
